/// Generated by AssetsRefGenerator on 2020/07/24
class Res {
  static const String icon_arrow_left = "asset/image/icon_arrow_left.png";
  static const String icon_check_keybind_act = "asset/image/icon_check_keybind_act.png";
  static const String icon_eye_close = "asset/image/icon_eye_close.png";
  static const String icon_eye_open = "asset/image/icon_eye_open.png";
  static const String icon_license_checked = "asset/image/icon_license_checked.png";
  static const String icon_license_uncheck = "asset/image/icon_license_uncheck.png";
  static const String showviewvisible = "asset/image/showviewvisible.png";
  static const String showviewvisible_1 = "asset/image/showviewvisible_1.png";
}
